apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: sme-azurefile-sc
provisioner: file.csi.azure.com
allowVolumeExpansion: true
parameters:
  resourceGroup: sme_aks_bpinheiro_rg
  storageAccount: seeacademyhw2bpinheiro
  #server: <storageAccountName>.file.core.windows.net
reclaimPolicy: Delete
volumeBindingMode: Immediate
mountOptions:
  - dir_mode=0777
  - file_mode=0777
  - uid=0
  - gid=0
  - mfsymlinks
  - cache=strict  # https://linux.die.net/man/8/mount.cifs
  - nosharesock  # reduce probability of reconnect race
  - actimeo=30  # reduce latency for metadata-heavy workload