apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: dev-team-sa-dev-role
  namespace: dev
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs: ["*"]
- apiGroups:
  - apps
  resources:
  - deployments
  verbs: ["*"]