apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: sme-azurefile-pvc
  namespace: prod
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: sme-azurefile-sc