apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-sa-dev-rolebinding
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-team-sa-dev-role
subjects:
- kind: ServiceAccount
  name: dev-team-sa
  namespace: default