apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: dev-team-sa-prod-rolebinding
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: dev-team-sa-prod-role
subjects:
- kind: ServiceAccount
  name: dev-team-sa
  namespace: default